force-app/main/default/objects/Calculator__c/Calculator__c.object-meta.xml
<CustomObject>
    <label>Calculator</label>
    <nameField>
        <displayFormat>Calc{0000}</displayFormat>
        <label>Calculator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calculators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calculator__c/fields/Difference__c.field-meta.xml
<CustomField>
    <fullName>Difference__c</fullName>
    <label>Difference</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/NumberA__c.field-meta.xml
<CustomField>
    <fullName>NumberA__c</fullName>
    <label>Number A</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/NumberB__c.field-meta.xml
<CustomField>
    <fullName>NumberB__c</fullName>
    <label>Number B</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/Quotient__c.field-meta.xml
<CustomField>
    <fullName>Quotient__c</fullName>
    <label>Quotient</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/Sum__c.field-meta.xml
<CustomField>
    <fullName>Sum__c</fullName>
    <label>Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/verify_pack/IllegalArgumentsTest.cls
@isTest
private class IllegalArgumentsTest {

    @isTest
	private static void shouldQuotientBeNullForDivisionByZero() {
        //given
        Calculator__c calc = createCalculator(18, 0);

        //when
        Test.startTest();
            Insert calc;
        Test.stopTest();

        Calculator__c result = getCalculatorById(calc.Id);    
        //then
        System.assertEquals(null, result.Quotient__c);
    }
    
    private static Calculator__c createCalculator(Double numberA, Double numberB) {
        return new Calculator__c(
            NumberA__c = numberA,
            NumberB__c = numberB
        );
    }

    private static Calculator__c getCalculatorById(Id calcId) {
        return [
            SELECT
                NumberA__c,
                NumberB__c,
                Sum__c,
                Difference__c,
                Product__c,
                Quotient__c
            FROM
                Calculator__c
            WHERE
                Id = :calcId
        ];
    }

}