force-app/main/default/objects/Calculator__c/Calculator__c.object-meta.xml
<CustomObject>
    <label>Calculator</label>
    <nameField>
        <displayFormat>Calc{0000}</displayFormat>
        <label>Calculator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calculators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calculator__c/fields/Difference__c.field-meta.xml
<CustomField>
    <fullName>Difference__c</fullName>
    <label>Difference</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/NumberA__c.field-meta.xml
<CustomField>
    <fullName>NumberA__c</fullName>
    <label>Number A</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/NumberB__c.field-meta.xml
<CustomField>
    <fullName>NumberB__c</fullName>
    <label>Number B</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/Quotient__c.field-meta.xml
<CustomField>
    <fullName>Quotient__c</fullName>
    <label>Quotient</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/Sum__c.field-meta.xml
<CustomField>
    <fullName>Sum__c</fullName>
    <label>Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/verify_pack/RandomNumbersTest.cls
@isTest
private class RandomNumbersTest {

    @isTest
    private static void shouldAddTwoNumbers() {
        //given
        Integer numberA = getRandom();
        Integer numberB = getRandom();
        Calculator__c calc = createCalculator(numberA, numberB);

        //when
        Test.startTest();
            Insert calc;
        Test.stopTest();

        Calculator__c result = getCalculatorById(calc.Id);    
        //then
        System.assertEquals(numberA + numberB, result.Sum__c);
    }

    @isTest
    private static void shouldSubtractTwoNumbers() {
        //given
        Integer numberA = getRandom();
        Integer numberB = getRandom();
        Calculator__c calc = createCalculator(numberA, numberB);

        //when
        Test.startTest();
            Insert calc;
        Test.stopTest();

        Calculator__c result = getCalculatorById(calc.Id);    
        //then
        System.assertEquals(numberA - numberB, result.Difference__c);
    }

    @isTest
    private static void shouldMultiplyTwoNumbers() {
        //given
        Integer numberA = getRandom();
        Integer numberB = getRandom();
        Calculator__c calc = createCalculator(numberA, numberB);

        //when
        Test.startTest();
            Insert calc;
        Test.stopTest();

        Calculator__c result = getCalculatorById(calc.Id);    
        //then
        System.assertEquals(numberA * numberB, result.Product__c);
    }

    @isTest
    private static void shouldDivideTwoNumbers() {
        //given
        Integer numberA = getRandom();
        Integer numberB = getRandom();
        Calculator__c calc = createCalculator(numberA, numberB);

        //when
        Test.startTest();
            Insert calc;
        Test.stopTest();

        Calculator__c result = getCalculatorById(calc.Id);
        Decimal numberADec = Decimal.valueOf(numberA);
        Decimal numberBDec = Decimal.valueOf(numberB);
        Decimal expected = numberADec / numberBDec;

        //then
        System.assertEquals(expected.setScale(2), result.Quotient__c.setScale(2));
    }

    private static Calculator__c createCalculator(Double numberA, Double numberB) {
        return new Calculator__c(
            NumberA__c = numberA,
            NumberB__c = numberB
        );
    }

    private static Calculator__c getCalculatorById(Id calcId) {
        return [
            SELECT
                NumberA__c,
                NumberB__c,
                Sum__c,
                Difference__c,
                Product__c,
                Quotient__c
            FROM
                Calculator__c
            WHERE
                Id = :calcId
        ];
    }
    
    private static Integer getRandom() {
        return Integer.valueof((Math.random() * 100)) + 1;
    }

}