force-app/main/default/objects/Calculator__c/Calculator__c.object-meta.xml
<CustomObject>
    <label>Calculator</label>
    <nameField>
        <displayFormat>Calc{0000}</displayFormat>
        <label>Calculator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calculators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calculator__c/fields/Difference__c.field-meta.xml
<CustomField>
    <fullName>Difference__c</fullName>
    <label>Difference</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/NumberA__c.field-meta.xml
<CustomField>
    <fullName>NumberA__c</fullName>
    <label>Number A</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/NumberB__c.field-meta.xml
<CustomField>
    <fullName>NumberB__c</fullName>
    <label>Number B</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/Quotient__c.field-meta.xml
<CustomField>
    <fullName>Quotient__c</fullName>
    <label>Quotient</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Calculator__c/fields/Sum__c.field-meta.xml
<CustomField>
    <fullName>Sum__c</fullName>
    <label>Sum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CalculatorTest.cls
@isTest
private class CalculatorTest {

    @isTest
    private static void shouldAddTwoNumbers() {
        //given
        Calculator__c calc = createCalculator(2, 3);

        //when
        Test.startTest();
            Insert calc;
        Test.stopTest();

        Calculator__c result = getCalculatorById(calc.Id);    
        //then
        System.assertEquals(5, result.Sum__c);
    }

    @isTest
    private static void shouldSubtractTwoNumbers() {
        //given
        Calculator__c calc = createCalculator(9, 2);

        //when
        Test.startTest();
            Insert calc;
        Test.stopTest();

        Calculator__c result = getCalculatorById(calc.Id);    
        //then
        System.assertEquals(7, result.Difference__c);
    }

    @isTest
    private static void shouldMultiplyTwoNumbers() {
        //given
        Calculator__c calc = createCalculator(4, 3);

        //when
        Test.startTest();
            Insert calc;
        Test.stopTest();

        Calculator__c result = getCalculatorById(calc.Id);    
        //then
        System.assertEquals(12, result.Product__c);
    }

    @isTest
    private static void shouldDivideTwoNumbers() {
        //given
        Calculator__c calc = createCalculator(18, 3);

        //when
        Test.startTest();
            Insert calc;
        Test.stopTest();

        Calculator__c result = getCalculatorById(calc.Id);    
        //then
        System.assertEquals(6, result.Quotient__c);
    }

    @isTest
    private static void shouldProcessOperationsOnUpdate() {
        //given
        Calculator__c calc = createCalculator(1, 1);
        Insert calc;

        //when
        Test.startTest();
            calc.NumberA__c = 20;
            calc.NumberB__c = 5;
            update calc;
        Test.stopTest();

        Calculator__c result = getCalculatorById(calc.Id);    
        //then
        System.assertEquals(25, result.Sum__c);
        System.assertEquals(15, result.Difference__c);
        System.assertEquals(100, result.Product__c);
        System.assertEquals(4, result.Quotient__c);
    }

    private static Calculator__c createCalculator(Double numberA, Double numberB) {
        return new Calculator__c(
            NumberA__c = numberA,
            NumberB__c = numberB
        );
    }

    private static Calculator__c getCalculatorById(Id calcId) {
        return [
            SELECT
                NumberA__c,
                NumberB__c,
                Sum__c,
                Difference__c,
                Product__c,
                Quotient__c
            FROM
                Calculator__c
            WHERE
                Id = :calcId
        ];
    }

}